spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/payment"
    username: postgres
    password: postgres
app:
  import:
#    file: "import.csv"
    headerLines: 3
    datePattern: "yyyy-MM-dd"
    fieldSeparator: ";"
    thousandsSeparator: "."
    decimalSeparator: ","
